# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_welcome:
    pattern:  /
    defaults: { _controller: TecnotekExpedienteBundle:Default:index }

#_demo_secured:
#    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
#    type:     annotation

#_demo:
#    resource: "@AcmeDemoBundle/Controller/DemoController.php"
#    type:     annotation
#    prefix:   /demo

#TECNOTEK :: EXPEDIENTE :: ROUTING
TecnotekExpedienteBundle:
    resource: "@TecnotekExpedienteBundle/Resources/config/routing.yml"
    prefix:   /expediente